const express=require('express');const http=require('http');const {Server}=require('socket.io');
const app=express();const server=http.createServer(app);const io=new Server(server,{cors:{origin:'*'}});app.use(express.static('public'));
const rooms=new Map();
function code(){return Math.floor(1000+Math.random()*9000).toString()}
function deck(){const colors=['R','Y','G','B'];const d=[];for(const c of colors){for(let n=0;n<=9;n++){d.push({t:'num',c,v:n,id:c+n+'a'}); if(n) d.push({t:'num',c,v:n,id:c+n+'b'});} for(let i=0;i<2;i++){d.push({t:'skip',c,v:'⛔',id:c+'skip'+i},{t:'rev',c,v:'↺',id:c+'rev'+i},{t:'draw2',c,v:'+2',id:c+'d2'+i});}} for(let i=0;i<4;i++) d.push({t:'wild',c:'K',v:'🌈',id:'wild'+i},{t:'draw4',c:'K',v:'+4',id:'d4'+i});return d.sort(()=>Math.random()-.5)}
function pub(r){return {code:r.code,players:r.players.map(p=>({name:p.name,cards:p.hand.length,score:p.score,uno:p.uno})),started:r.started,turn:r.turn,dir:r.dir,top:r.discard.at(-1),pending:r.pending,locked:r.locked,log:r.log.slice(-8),winner:r.winner}}
function playable(card,r){const top=r.discard.at(-1); if(r.pending>0){if(r.locked==='draw4') return card.t==='draw4'; return card.t==='draw2'||card.t==='draw4'} return card.c==='K'||card.c===top.c||card.v===top.v||card.t===top.t}
function nextIdx(r,i=r.turn,step=1){let n=r.players.length;return (i+r.dir*step+n*99)%n}
function deal(r){r.deck=deck();r.discard=[];r.players.forEach(p=>{p.hand=[];p.uno=false;for(let i=0;i<7;i++)p.hand.push(r.deck.pop())});let first;do{first=r.deck.pop()}while(first.c==='K');r.discard.push(first);r.turn=0;r.dir=1;r.pending=0;r.locked=null;r.started=true;r.winner=null;r.log=['Partie lancée'];}
function draw(r,p,n){for(let i=0;i<n;i++){if(!r.deck.length){const top=r.discard.pop();r.deck=r.discard.sort(()=>Math.random()-.5);r.discard=[top]}p.hand.push(r.deck.pop())}}
function endHand(r,finisher){r.log.push(`${finisher.name} finit la manche !`);for(const p of r.players){if(p===finisher)continue;let pts=0;for(const c of p.hand){if(c.t==='num')pts+=c.v;else if(c.c==='K')pts+=50;else pts+=25}p.score+=pts;}const loser=r.players.find(p=>p.score>=500);if(loser){r.winner=`${loser.name} atteint 500 points et perd la partie`;r.started=false}else deal(r)}
io.on('connection',s=>{s.on('create',({name},cb)=>{let c;do c=code();while(rooms.has(c));const r={code:c,players:[{id:s.id,name:name||'Joueur',hand:[],score:0,uno:false}],started:false,log:[`Salle ${c} créée`]};rooms.set(c,r);s.join(c);cb({ok:true,code:c});io.to(c).emit('state',pub(r));});
s.on('join',({name,code},cb)=>{const r=rooms.get(code);if(!r)return cb({ok:false,msg:'Salle introuvable'});if(r.started)return cb({ok:false,msg:'Partie déjà lancée'});r.players.push({id:s.id,name:name||'Joueur',hand:[],score:0,uno:false});s.join(code);r.log.push(`${name} rejoint`);cb({ok:true});io.to(code).emit('state',pub(r));});
s.on('start',code=>{const r=rooms.get(code);if(r&&r.players[0].id===s.id&&r.players.length>=2){deal(r);io.to(code).emit('state',pub(r));r.players.forEach(p=>io.to(p.id).emit('hand',p.hand));}});
s.on('play',({code,idx,color})=>{const r=rooms.get(code);if(!r||!r.started)return;const p=r.players.find(x=>x.id===s.id);const pi=r.players.indexOf(p);if(!p)return;const card=p.hand[idx];if(!card)return;const top=r.discard.at(-1);const instant=card.c===top.c&&card.v===top.v&&card.t===top.t; if(pi!==r.turn&&!instant)return; if(!instant&&!playable(card,r))return;
p.hand.splice(idx,1); if(card.c==='K'&&color)card.c=color; r.discard.push(card);p.uno=false;r.log.push(`${p.name} joue ${card.v} ${card.c}`);
if(card.t==='draw2'){r.pending+=2;r.locked=r.locked||'draw2';r.turn=nextIdx(r,pi)} else if(card.t==='draw4'){r.pending+=4;r.locked='draw4';r.turn=nextIdx(r,pi)} else {r.pending=0;r.locked=null;if(card.t==='skip')r.turn=nextIdx(r,pi,2); else if(card.t==='rev'){r.dir*=-1;r.turn=nextIdx(r,pi)} else r.turn=nextIdx(r,pi)}
if(!p.hand.length)return endHand(r,p),io.to(code).emit('state',pub(r));io.to(code).emit('state',pub(r));r.players.forEach(pl=>io.to(pl.id).emit('hand',pl.hand));});
s.on('draw',code=>{const r=rooms.get(code);if(!r||!r.started)return;const p=r.players[r.turn];if(p.id!==s.id)return;const n=r.pending||1;draw(r,p,n);r.log.push(`${p.name} pioche ${n}`);r.pending=0;r.locked=null;r.turn=nextIdx(r);io.to(code).emit('state',pub(r));r.players.forEach(pl=>io.to(pl.id).emit('hand',pl.hand));});
s.on('uno',code=>{const r=rooms.get(code);const p=r?.players.find(x=>x.id===s.id);if(p&&p.hand.length===1){p.uno=true;r.log.push(`${p.name} dit UNO !`);io.to(code).emit('state',pub(r));}});
s.on('penalty',({code,target})=>{const r=rooms.get(code);if(!r)return;const p=r.players[target];if(p&&p.hand.length===1&&!p.uno){draw(r,p,2);r.log.push(`${p.name} oublie UNO : +2 et passe son tour`);if(r.turn===target)r.turn=nextIdx(r);io.to(code).emit('state',pub(r));r.players.forEach(pl=>io.to(pl.id).emit('hand',pl.hand));}});
s.on('disconnect',()=>{for(const r of rooms.values()){const p=r.players.find(x=>x.id===s.id);if(p){r.log.push(`${p.name} déconnecté`);io.to(r.code).emit('state',pub(r));}}});});
server.listen(process.env.PORT||3000,()=>console.log('UNO Perso lancé'));
